HW 2
MikhailStatsenko/link-tracker pull request #2
Opened 2024-02-25 15:48 UTC by MikhailStatsenko

2024-02-26 18:11 UTC, SHvatov requested changes
@MikhailStatsenko оставил пару комментариев, посмотри их, пожалуйста.

2024-02-26 18:11 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/GitHubClient.java
> +public interface GitHubClient {
А тебе точно нужен этот интерфейс?)

2024-02-26 18:11 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/GitHubClientImpl.java
> +    private String gitHubBaseUrl = "https://api.github.com";
Вообще такое чаще всего выносится на уровень конфигурации как дефолтное значение. В коде мы стараемся не хранить такие литералы.

2024-02-26 18:11 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/GitHubClientImpl.java
> +            .onStatus(HttpStatusCode::isError, clientResponse -> clientResponse.bodyToMono(RuntimeException.class)
Не уверен, что такое сработает и он сможет нормально скастить тело ответа в исключение. И вторым flatMap'ом ты затираешь оригинальное исключение.

2024-02-26 18:11 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/configuration/ApplicationConfig.java
> +    @Bean
Зачем?

2024-02-26 18:11 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/configuration/ApplicationConfig.java
>      public record Scheduler(boolean enable, @NotNull Duration interval, @NotNull Duration forceCheckDelay) {
Названия стоит конкретизировать, шедулеров может быть много. И префиск тоже нужно указать ему конкретный, к примеру `app.links-scheduler`.

2024-02-26 19:59 UTC, MikhailStatsenko commented on scrapper/src/main/java/edu/java/scrapper/configuration/ApplicationConfig.java
> +    @Bean
Без этого не получается обратиться к значению в @Scheduled и приложение падает (на скрине). Предложили объявить бин scheduler, я так и сделал, все заработало. Лучше сделать по-другому? 
Я видел что в чате люди пытались установить значение fixedDelayString в @Scheduled напрямую из application.yml, но тогда я не совсем понимаю зачем в задании просят создать record Scheduler

<img width="1292" alt="image" src="https://github.com/MikhailStatsenko/link-tracker/assets/112765729/1ef7d3c7-1095-461c-b5b3-c3bf0ba5b78d">

2024-02-26 20:10 UTC, MikhailStatsenko commented on scrapper/src/main/java/edu/java/scrapper/client/GitHubClient.java
> +public interface GitHubClient {
После поста в телеге понял, что я видимо слишком усердствовал с добавлением интерфейсов везде, где можно) Буду исправляться

2024-02-26 20:13 UTC, MikhailStatsenko commented on scrapper/src/main/java/edu/java/scrapper/configuration/ApplicationConfig.java
>      public record Scheduler(boolean enable, @NotNull Duration interval, @NotNull Duration forceCheckDelay) {
В задании просят именно scheduler, но замечание вполне справедливое, исправлю

2024-02-27 09:25 UTC, MikhailStatsenko commented on scrapper/src/main/java/edu/java/scrapper/client/GitHubClientImpl.java
> +    private String gitHubBaseUrl = "https://api.github.com";
Вынес дефолтное значение в конфигурацию, но у меня возникли проблемы с тем чтобы его красиво оттуда достать.
Если использовать @Value перед параметром конструктора, передаваемое значение затирается и мы всегда используем дефолтный url, если использовать @Value над полем класса, то оно инициализируется уже после того как отработал конструктор, поэтому мы не можем выполнить проверку передаваемого параметра на null и в случае чего подставить дефолтное значение (оно в этот момент тоже равно null). 
Я еще подумал что можно использовать SpEL внутри @Value чтобы проверить, что поле равно null или пустое и заменить его на дефолтное, но у меня не получилось обратиться к значению поля в рамках аннотации. 
В итоге сделал два поля: для дефолтного значения и для базового url из конструктора. Оно конечно работает, но это наверное не самое хорошее решение

2024-02-28 13:20 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/GitHubClient.java
> +public interface GitHubClient {
Да не, все персонажи вымышленны, а совпадения случайны)

2024-02-28 13:26 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/configuration/ApplicationConfig.java
> +    @Bean
Понятно, но на будущее:
1. В задании просят вас указать интервал через SPeL, но я советую использовать именно проперти - они гораздо реже меняются, а переменную переименовать всякий горазд. Да и намного понятнее, где искать конфиги. 
2. У аннотации `Bean` `@Target({ElementType.METHOD, ElementType.ANNOTATION_TYPE})`, что говорит о том, что ее использовать можно только на методах / аннотациях. Сейчас оно работает, потому что аннотация на рекорде пропагируется с поле на генерируемые методы (https://stackoverflow.com/questions/67074911/what-annotation-targets-are-applicable-to-java-records). Лучше так не делать - очень неочевидное поведение, особенно для тех, кто не знаком с внутрянкой JVM. Хочешь объявить бин - создавай метод или используй `@Component/Service/etc`.

2024-02-28 13:28 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/GitHubClientImpl.java
> +    private String gitHubBaseUrl = "https://api.github.com";
1. В `Value` можно указать дефолтное значение через `"${property:<default value>}"`
2. Есть вот такая анноташка - @DefaulValue

2024-02-28 13:28 UTC, SHvatov requested changes
@MikhailStatsenko отписался в комментах, посмотри, плиз

2024-02-28 20:52 UTC, MikhailStatsenko commented on scrapper/src/main/java/edu/java/scrapper/configuration/ApplicationConfig.java
> +    @Bean
Я ведь правильно понял что тут ничего менять уже не нужно? Я для себя попробовал достать через проперти так: `@Scheduled(fixedDelayString = "${app.links-scheduler.interval}")` и там единственная проблема возникает с тем что в `application.yml` указано 10s, но это можно решить указав время сразу в миллисекундах или как-нибудь отпарсив значение. Просто если я так сделаю, то не совсем по заданию получится

2024-02-28 21:01 UTC, MikhailStatsenko commented on scrapper/src/main/java/edu/java/scrapper/client/GitHubClientImpl.java
> +    private String gitHubBaseUrl = "https://api.github.com";
Я снова по-разному попробовал, но с @DefaultValue так и не сложилось. Сильно много примеров ее использования мне найти не удалось, но как я понял она сработала бы если бы я ее использовал в классе, помеченном `@Component` или чем-то аналогичным. А так как бины по заданию создаются в классе-конфигурации через new, дефолтное значение не подставляется. 
По итогу чтобы не делать два поля (для дефолтного и базового url) и не использовать лишний раз `@PostConstruct`, решил внедрять значения в `ClientConfiguration` через `@Value`. Так вроде и с логической точки зрения проблем нет и компактнее получается

2024-02-29 19:08 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/configuration/ApplicationConfig.java
> +    @Bean
Ничего страшного, закон, как говорится, тут я)
![image](https://github.com/MikhailStatsenko/link-tracker/assets/15994914/2470477e-9bee-41b1-88f5-ae62d2470425)

2024-02-29 19:08 UTC, SHvatov approved these changes
@MikhailStatsenko 👌, можно вливать.

2024-03-01 06:09 UTC, merged