Hw3
MikhailStatsenko/link-tracker pull request #3
Opened 2024-03-03 19:04 UTC by MikhailStatsenko

2024-03-05 20:47 UTC, SHvatov requested changes
@MikhailStatsenko 🚀 , оставил пару минорных комментариев - погляди их, пожалуйста.

2024-03-05 20:47 UTC, SHvatov commented on bot/pom.xml
> +                <artifactId>openapi-generator-maven-plugin</artifactId>
🔥 🚒

2024-03-05 20:47 UTC, SHvatov commented on bot/pom.xml
> +<!--            <plugin>-->
вот это можно в топку)

2024-03-05 20:47 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/service/command/ListCommand.java
> +            return new SendMessage(chatId, ERROR_MESSAGE);
Еще бы сообщение залогировать, чтобы потом было проще разбираться.

2024-03-05 20:47 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/service/command/ListCommand.java
> +            return new SendMessage(chatId, ERROR_MESSAGE);
И я бы обработку исключений вынес бы куда-нибудь повыше, и там бы все обрабатывал.

2024-03-05 20:47 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/service/command/StartCommand.java
> +            return new SendMessage(chatId, USER_ALREADY_EXISTS);
Вот тут не совсем верно. А если сервис просто лежит и nginx отдаст тебе 502?

2024-03-05 20:47 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/service/command/StartCommand.java
> +            return new SendMessage(chatId, USER_ALREADY_EXISTS);
Аналогично в других обработках ошибок.

2024-03-05 20:47 UTC, SHvatov commented on scrapper/pom.xml
> +<!--                <groupId>org.openapitools.openapidiff</groupId>-->
Тоже в 🗑️

2024-03-05 20:47 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/exception/handler/ScrapperControllerExceptionHandler.java
> +    private ApiErrorResponse getErrorResponse(Throwable exception, String description, HttpStatus status) {
Хорошая практика держать приватные методы после публичных.

2024-03-10 19:31 UTC, MikhailStatsenko commented on bot/src/main/java/edu/java/bot/service/command/ListCommand.java
> +            return new SendMessage(chatId, ERROR_MESSAGE);
Сделал так, что исключения, которые мы не ожидаем и от scrapper'а и не планируем обрабатывать особым образом в рамках конкретной команды попадают в `UserMessageProcessor`, там логируются и бот выдает пользователю сообщение об абстрактной ошибке

2024-03-10 19:38 UTC, MikhailStatsenko commented on bot/src/main/java/edu/java/bot/service/command/StartCommand.java
> +            return new SendMessage(chatId, USER_ALREADY_EXISTS);
Добавил `ApiBadRequestException` и `ApiNotFoundException` которые создаются при обработке соответствующих статусов ответа в `ScrapperClient` для отслеживания подобных ситуаций. В командах ловлю исключение и выдаю пользователю подходящее сообщение

2024-03-11 20:17 UTC, SHvatov approved these changes
@MikhailStatsenko 👌, но покрытие скраппера почти на нуле. В этот раз закроем глаза, но впредь будьте осторожны.

2024-03-17 06:19 UTC, merged