hw5
MikhailStatsenko/link-tracker pull request #5
Opened 2024-03-17 20:27 UTC by MikhailStatsenko

2024-03-25 05:55 UTC, SHvatov commented
@MikhailStatsenko 👋 Как обсуждали, хорошо бы докинуть юнитов, а то покрытие ниже 50%.

2024-03-25 06:02 UTC, SHvatov requested changes
@MikhailStatsenko 👍, оставил пару минорных комментариев. И докинь, плиз, тестики - снижать баллы из-за этого не хочется)

2024-03-25 06:02 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/controller/ScrapperController.java
> +        List<Link> links = linkService.listAll(tgChatId);
`listAll` -> `findAll`, понятнее и это стандартное название для подобного рода методов.

2024-03-25 06:02 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/repository/JdbcChatRepository.java
> +            "SELECT chat_id FROM chat_link WHERE link_id = ?",
Вместо ? советую использовать именованные параметры, легче потом понять, кто куда маппится, и заодно явно видно, что не хватает каких-то параметров.

2024-03-25 06:02 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/repository/JdbcChatRepository.java
> +                new BeanPropertyRowMapper<>(Chat.class),
Прикольная штучка, 👍

2024-03-25 06:02 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/repository/JdbcLinkRepository.java
> +        if (savedLink.isEmpty()) {
Вот тут при параллельном исполнении все посыпется, потому что второй инсерт породит unique constraint violation. Сейчас это не критично, просто на будущее.

2024-03-25 06:02 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/service/jdbc/JdbcChatService.java
> +public class JdbcChatService implements ChatService {
1. Держать в названии, что конкретно используется под капотом - избыточно_
2. Я бы сервис сделал один, а вот уже под капотом менял реализацию репозитория. Я более чем уверен, что не JDBC-ный сервис у тебя будет выглядеть ровно так же.

2024-03-28 21:02 UTC, MikhailStatsenko commented
@SHvatov вроде все что надо подправил, но так получилось, что я влил 5 бонус сюда раньше времени и понял это когда было уже слишком поздно, поэтому все 4 тыс. строк изменений тут :(

Добавлю скрины работы бота, которых не хватало в 5 бонусе:
<img width="602" alt="image" src="https://github.com/MikhailStatsenko/link-tracker/assets/112765729/176b9e1c-df4a-4557-bc2c-fe5e1f9b7f2e">
<img width="602" alt="image" src="https://github.com/MikhailStatsenko/link-tracker/assets/112765729/780059e4-48ca-48fa-8884-c724547974cd">

Я еще немного не понимаю почему тут отображается такое низкое покрытие, хотя я тесты дописал, в idea вроде все хорошо выглядит:
<img width="684" alt="image" src="https://github.com/MikhailStatsenko/link-tracker/assets/112765729/71ee92fe-971c-4649-b088-5216d895e229">
<img width="684" alt="image" src="https://github.com/MikhailStatsenko/link-tracker/assets/112765729/5dc7f84e-155b-442f-b283-b7dd428d2734">

2024-03-28 21:07 UTC, MikhailStatsenko commented on scrapper/src/main/java/edu/java/scrapper/service/jdbc/JdbcChatService.java
> +public class JdbcChatService implements ChatService {
Там в задании просили писать именно так, то есть JdbcLinkService, JooqLinkService, JpaLinkService, и в 6 задании просят сделать выбор реализации сервиса через конфигурацию, но мне такое название тоже показалось странным. Я переделал и дальше буду делать настраиваемым выбор реализации репозитория видимо

2024-03-31 10:42 UTC, SHvatov approved these changes
@MikhailStatsenko 👌, можно мержить. Однако минус балл будет за покрытие юнитам(

2024-03-31 11:12 UTC, merged