hw 8
MikhailStatsenko/link-tracker pull request #9
Opened 2024-04-07 18:55 UTC by MikhailStatsenko

- добавил kafka и zookeeper в compose.yml
- добавил конфигурацию producer в scrapper, конфигурацию producer и consumer в бота
- реализовал отправку сообщений об обновлениях в очередь kafka через kafkaTemplate
- добавил выбор способа отправки сообщений об обновлениях через конфигурацию 
- реализовал Dead Letter Queue

2024-04-14 14:45 UTC, SHvatov requested changes
@MikhailStatsenko в целом ОК, но вот кейс с невалидным сообщением ты обработал не полностью. Почитай вот эту [статью](https://www.baeldung.com/spring-kafka-deserialization-errors) и поправь это плиз.

2024-04-14 14:45 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/configuration/KafkaConfiguration.java
> +    public Map<String, Object> consumerConfigs() {
А почему автоконфигурацию не заюзал?

2024-04-14 14:45 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/service/kafka/BotQueueConsumer.java
> +        } catch (Exception e) {
Вот так ошибку десериализации ты не отловишь, а по заданию - надо бы. Поправь и добавь тестик интеграционный на это.

2024-04-19 17:31 UTC, MikhailStatsenko commented on bot/src/main/java/edu/java/bot/configuration/KafkaConfiguration.java
> +    public Map<String, Object> consumerConfigs() {
Делал по семинару и гуглу, там вроде в основном так настраивают

2024-04-19 17:37 UTC, MikhailStatsenko commented on bot/src/main/java/edu/java/bot/service/kafka/BotQueueConsumer.java
> +        } catch (Exception e) {
По статье сделал `CommonErrorHandler`, но я не смог найти как внутри него можно обратиться к сообщению, которое вызвало ошибку, поэтому ошибка десериализации обрабатывается через него, а остальные ошибки обрабатываю так же через try/catch, чтобы добавлять их в dlq

2024-04-21 17:30 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/configuration/KafkaConfiguration.java
> +    public Map<String, Object> consumerConfigs() {
ок, но на будущее - у спринга из коробки есть [около-идеальная автоконфигурация](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/kafka/KafkaAutoConfiguration.html).

2024-04-21 17:31 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/service/kafka/BotQueueConsumer.java
> +        } catch (Exception e) {
тоже норм 👍

2024-04-21 17:31 UTC, SHvatov approved these changes

2024-05-02 15:55 UTC, merged